#!/bin/bash
# Simple task automated and silly script formatted by Jake
#~~~~~.bashrc changer~~~~
# Optional bashrc file made by helmuthdu. One of my favorites. Uncomment to win
#==============================================================================
#current=`md5sum ~/.bashrc | cut -d' ' -f1`
#new='4923a24ef5cc07925f66bb2cd3e512d7'
#if [ $current = $new  ]; then
#	:
#else
#	rm ~/.bashrc
#	wget https://raw.githubusercontent.com/helmuthdu/dotfiles/master/.bashrc -O ~/.bashrc
#	source ~/.bashrc
#fi
#==============================================================================

# Updater
echo -e "\e[92mAptitude Updater, cause life is too short for this shit!"
echo -e "\e[7mBrought to you by Jake & Caffeine!\e[27m"
echo -e "\e[96m+++ Hitting Repositories...\e[35m"
sudo apt-get update
echo -e "\e[96m+++ Grabbing New Packages...\e[35m"
sudo apt-get upgrade -y
echo -e "\e[96m+++ Installing locate, cause c'mon, you better have it.\e[35m"
sudo apt-get install locate -y
echo -e "\e[96m+++ Checking for Distro Upgrades...\e[35m"
sudo apt-get dist-upgrade -y
echo -e "\e[96m+++ Taking out the trash...\e[35m"
sudo apt-get autoremove -y
echo -e "\e[92m All done! Now do something productive! ;)\e[0m"

# Motivator
# Check for Live Persistence
if [ -e /lib/live/mount/persistence  ]; then
	MAU="$(locate Motivational-Aptitude-Updater/updater | cut -d$'\n' -f2)"
	export PATH=$MAU:$PATH
	LOC="$(sudo locate quotesMAU10.txt | cut -d$'\n' -f2)"
else
	MAU="$(locate Motivational-Aptitude-Updater/updater | cut -d$'\n' -f1)"
	export PATH=$MAU:$PATH
	LOC="$(sudo locate quotesMAU10.txt | cut -d$'\n' -f1)"
fi
shuf -n 1 $LOC
